excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://AfshinNasseri.github.io
title: AfshinNasseri
tagline: A log of everyday life
description: <br />Afshin Nasseri, MD is a well-known "Internal Medicine" physician.Afshin Nasseri spent 23 years in his practice and training in Internal Medicine field. he is a member of the group of Practice "East Coast Primary Care, Inc."He has ample of experience in the Internal Medicine field and has given valuable services to many trusted hospitals and medical authorities located at Warwick, Rhode Island and other states of the U.S.Furthermore, he accepts only medicare assignments (which means he accepts the Medicare-approved amount; you will not be billed for any more than the Medicare deductible and coinsurance). <br />
paginate: 5